version: "3.8"

networks:
  novanet:
    driver: bridge

services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis_data:/data/
    networks:
      - novanet
    ports:
      - '6379:6379'
    restart: always

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/
    networks:
      - novanet
    ports:
      - '8000:8000'
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./knowledge_base/:/app/knowledge_base/
    ports:
      - 8888:8888
    networks:
      - novanet
    depends_on:
      - redis
      - chroma
    user: root
    env_file:
      - .env

  tts-api:
    build: './tts'
    ports:
      - '8889:8889'
    networks:
      novanet:
        aliases:
              - tts.local
  # stt-api:
  #   build: './stt'
  #   ports:
  #     - '8890:8890'  
  #   networks:
  #     novanet:
  #       aliases:
  #             - stt.local

volumes:
  redis_data:
  chroma_data: